language: ruby

rvm:
  - 2.6.6

services:
  - postgresql

bundler_args: --without production

before_install: gem install bundler

before_script: bundle exec rake db:create db:migrate

script: bundle exec rspec
